spring:
  application:
    name: myCamel
  profiles:
    # The commented value for `active` can be replaced with valid Spring profiles to load.
    # Otherwise, it will be filled in by maven when building the JAR file
    # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
    active: #spring.profiles.active#
  mvc:
    servlet:
      load-on-startup: 100
  datasource:
    driver-class-name: org.h2.Driver
    schema: classpath:db/schema-h2.sql
    data: classpath:db/data-h2.sql
    # No restrictions on table names
    url: jdbc:h2:mem:h2
    # No restrictions on username and password
    username: root
    password: 123
  h2:
    console:
      enabled: true
server:
  port: 8080

# application:
camel:
  component:
    servlet:
      mapping:
        context-path: /api/*
#mybatis
mybatis:
  type-aliases-package: com.scp.esb.entity
  mapper-locations: classpath:/mapper/*.xml
